spring.application.name=email-automation
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youremail
spring.mail.password=yourpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.admin.username=admin
app.admin.password=dhana123

#spring.security.user.name=customuser
#spring.security.user.password=custompassword
